General:
    project: CHIMERA2025_task2
    seed: 1234
    accelerator: gpu    # cpu, gpu
    precision: bf16    # 16, 32, bf16
    strategy: ddp    # ddp, fsdp
    num_nodes: 1
    epoch: &epoch 100
    check_val_every_n_epoch: 1
    debug: False
    lr_tune: False
    mode: train

Data:
    dataset:
        top_dir: /data/MICCAI2025_CHIMERA/task2/gigapath_slide_features_25000tiles
        train_datalist: datalist/train_datalist.csv
        valid_datalist: datalist/valid_datalist.csv
        num_classes: &num_classes 2
    dataloader:
        train:
            batch_size: 64
            num_workers: 4
            shuffle: True
        valid:
            batch_size: 64
            num_workers: 4
            shuffle: False
        predict:
            batch_size: 64
            num_workers: 4
            shuffle: False

Model:
    arch: mlp
    params:
        in_channels: 807    # 768+39
        hidden_channels: [256, *num_classes]
        norm_layer: nn.BatchNorm1d
        activation_layer: nn.ReLU
        inplace: None
        bias: True
        dropout: 0.1
    pretrained: None

Optimizer:
    optimizer:
        name: AdamW
        params:
            lr: !!python/float 5e-5
            weight_decay: !!python/float 1e-2
            betas: [0.9, 0.999]
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: *epoch
    accumulate_grad_batches: 1

Loss:
    lossfun_keys: [ce]
    lossfun_weights: [1.0]
    ce:
        lossfun: CrossEntropyLoss
        params: 
            weight: [1.0, 2.0]

